import * as React from "react";
import Head from "next/head";

import "!/styles/app.scss";

interface Props {
  title: string;
  children: React.ReactNode;
}

const Layout = ({ title, children }: Props) => (
  <div>
    <Head>
      <title>{title}</title>
      <meta charSet="utf-8" />
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      {/* the style.css is autogenerated */}
      <link rel="stylesheet" href="/_next/static/style.css" />
    </Head>

    {children}

    <footer>
      <a className="red" href="https://github.com/johhansantana/nast">
        Github
      </a>
    </footer>
  </div>
);
export default Layout;
